
(function(){
  const saved=localStorage.r4Theme||'dark';
  document.documentElement.dataset.theme=saved;
  window.toggleTheme=function(){
    const next=document.documentElement.dataset.theme==='light'?'dark':'light';
    document.documentElement.dataset.theme=next;
    localStorage.r4Theme=next;
    const b=document.getElementById('themeToggle');
    if(b) b.textContent=next==='light'?'🌙 Dark':'☀️ Light';
  };
  document.addEventListener('DOMContentLoaded',function(){
    const header=document.querySelector('header');
    if(header && !document.getElementById('themeToggle')){
      const b=document.createElement('button');
      b.id='themeToggle';
      b.className='theme-toggle';
      b.type='button';
      b.onclick=window.toggleTheme;
      b.textContent=(document.documentElement.dataset.theme==='light')?'🌙 Dark':'☀️ Light';
      header.appendChild(b);
    }
  });
})();
const OWNER_NUMBER='9929562585', OWNER_PASSWORD='NEHA@#LOBE', UPI_ID='9929562585@ptyes';
const BASE_KM=3, CUSTOMER_BASE=60, CUSTOMER_EXTRA=15, RIDER_BASE=40, RIDER_EXTRA=13, RADIUS=3;
const $=id=>document.getElementById(id); const money=n=>'₹'+Math.round(n);
const get=(k,d)=>JSON.parse(localStorage[k]||JSON.stringify(d)); const set=(k,v)=>localStorage[k]=JSON.stringify(v);
function seed(){if(!localStorage.r4Users){set('r4Users',{[OWNER_NUMBER]:{name:'Owner',mobile:OWNER_NUMBER,role:'admin',password:OWNER_PASSWORD,approved:true,passwordChanged:true},'9000000001':{name:'Demo Customer',mobile:'9000000001',role:'customer',password:'TEMP123',approved:true,passwordChanged:false},'9000000002':{name:'Demo Rider',mobile:'9000000002',role:'rider',password:'RIDER123',approved:true,passwordChanged:false,online:true,lat:31.1048,lng:77.1734,vehicle:'Bike'}})} if(!localStorage.r4Rides)set('r4Rides',[]); if(!localStorage.r4Apps)set('r4Apps',[])} seed();
function users(){return get('r4Users',{})} function saveUsers(u){set('r4Users',u)} function rides(){return get('r4Rides',[])} function saveRides(r){set('r4Rides',r)}
function fare(km){return km<=BASE_KM?CUSTOMER_BASE:CUSTOMER_BASE+(km-BASE_KM)*CUSTOMER_EXTRA} function riderPay(km){return km<=BASE_KM?RIDER_BASE:RIDER_BASE+(km-BASE_KM)*RIDER_EXTRA}
function dist(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function session(){const m=localStorage.r4Session,u=users()[m]; if(!u){location.href='index.html';return null} return u} function logout(){localStorage.removeItem('r4Session');location.href='index.html'}
function login(){const m=$('mobile').value.trim(),p=$('password').value,u=users()[m]; if(!u||u.password!==p)return alert('Wrong mobile/password'); if(!u.approved)return alert('Account pending approval'); localStorage.r4Session=m; if(u.role==='admin') location.href='admin.html'; else if(!u.passwordChanged) location.href='change-password.html'; else location.href=u.role+'.html'}
function signup(){let app={id:Date.now(),name:$('suName').value.trim(),mobile:$('suMobile').value.trim(),role:$('suRole').value,status:'pending',date:new Date().toLocaleString()}; if(!app.name||!app.mobile)return alert('Name/mobile डालो'); let a=get('r4Apps',[]);a.push(app);set('r4Apps',a); let msg=encodeURIComponent(`New ${app.role} signup\nName: ${app.name}\nMobile: ${app.mobile}\nPlease approve and give temporary password.`); window.open(`https://wa.me/91${OWNER_NUMBER}?text=${msg}`,'_blank'); alert('Request saved. WhatsApp owner ko bhej do.')} 
function changePassword(){let u=session(), us=users(), n=$('newPass').value, c=$('confirmPass').value; if(n.length<6)return alert('6 character se bada password rakho'); if(n!==c)return alert('Password match nahi'); us[u.mobile].password=n; us[u.mobile].passwordChanged=true; saveUsers(us); alert('Password changed'); location.href=u.role+'.html'}
let map, pickup={lat:31.1048,lng:77.1734,name:'Current Location'}, drop=null, routeLine=null, markers=[];
function initMap(){map=L.map('map').setView([pickup.lat,pickup.lng],13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map); locate(); renderRiders()}
function locate(){if(navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>{pickup={lat:p.coords.latitude,lng:p.coords.longitude,name:'Current Location'}; map.setView([pickup.lat,pickup.lng],15); draw()},()=>draw()); else draw()}
async function searchDrop(){let q=$('drop').value.trim(); if(!q)return; let r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(q)}&limit=1`); let j=await r.json(); if(!j[0])return alert('Location nahi mili'); drop={lat:+j[0].lat,lng:+j[0].lon,name:j[0].display_name}; draw(); calcRoute()}
function clearMarkers(){markers.forEach(m=>map.removeLayer(m));markers=[]} function draw(){if(!map)return; clearMarkers(); markers.push(L.marker([pickup.lat,pickup.lng]).addTo(map).bindPopup('Pickup')); if(drop)markers.push(L.marker([drop.lat,drop.lng]).addTo(map).bindPopup('Drop')); renderRiders(false)}
async function calcRoute(){if(!drop)return; let km=dist(pickup,drop); try{let r=await fetch(`https://router.project-osrm.org/route/v1/driving/${pickup.lng},${pickup.lat};${drop.lng},${drop.lat}?overview=full&geometries=geojson`);let j=await r.json(); if(j.routes&&j.routes[0]){km=j.routes[0].distance/1000; if(routeLine)map.removeLayer(routeLine); routeLine=L.geoJSON(j.routes[0].geometry,{style:{weight:5}}).addTo(map); map.fitBounds(routeLine.getBounds(),{padding:[20,20]})}}catch(e){} $('distance').textContent=km.toFixed(2)+' KM'; $('fare').textContent=money(fare(km)); $('riderPay').textContent=money(riderPay(km)); localStorage.r4LastKm=km}
function renderRiders(clear=true){if(!map)return; const us=users(); Object.values(us).filter(u=>u.role==='rider'&&u.online&&u.lat).forEach(r=>{let near=dist(pickup,{lat:r.lat,lng:r.lng}); let icon=L.divIcon({html:'🏍️',className:'',iconSize:[28,28]}); markers.push(L.marker([r.lat,r.lng],{icon}).addTo(map).bindPopup(`${r.name} - ${near.toFixed(1)} KM`))})}
function bookRide(){if(!drop)return alert('Drop location select करो'); const u=session(), km=+(localStorage.r4LastKm||dist(pickup,drop)); const ride={id:Date.now(),customer:u.mobile,customerName:u.name,pickup,drop,km,amount:fare(km),riderPay:riderPay(km),payment:$('payment').value,forWhom:$('forWhom').value,receiver:$('receiver').value,status:'searching',created:new Date().toLocaleString()}; let rr=rides(); rr.unshift(ride); saveRides(rr); alert('Ride booked. 3 KM ke andar rider ko ring jayegi.'); location.reload()}
function setupSwipe(){const s=$('swipe'),k=$('knob'); if(!s)return; let down=false,start=0; const move=x=>{let w=s.clientWidth-62,pos=Math.max(0,Math.min(w,x-start));k.style.transform=`translateX(${pos}px)`; if(pos>w*.82){down=false;bookRide()}}; k.onpointerdown=e=>{down=true;start=e.clientX}; window.onpointermove=e=>{if(down)move(e.clientX)}; window.onpointerup=()=>{down=false;k.style.transform='translateX(0)'}}
function loadCustomer(){let u=session(); if(!u.passwordChanged)return location.href='change-password.html'; $('hello').textContent='Hi, '+u.name; initMap(); setupSwipe(); let my=rides().filter(r=>r.customer===u.mobile); $('history').innerHTML=my.map(r=>`<div class=item><b>${r.pickup.name.split(',')[0]} → ${r.drop.name.split(',')[0]}</b><br>${r.km.toFixed(1)} KM • ${money(r.amount)} • ${r.status}</div>`).join('')||'<p class=hint>No rides yet</p>'}
function beep(){try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=880;g.gain.value=.08;o.start();setTimeout(()=>{o.stop();a.close()},350)}catch(e){}}
function loadRider(){let u=session(),us=users(); if(!u.passwordChanged)return location.href='change-password.html'; $('riderName').textContent=u.name; if(navigator.geolocation)navigator.geolocation.watchPosition(p=>{us=users(); us[u.mobile].lat=p.coords.latitude; us[u.mobile].lng=p.coords.longitude; saveUsers(us)}); showRiderOrders(); setInterval(showRiderOrders,3000)}
function showRiderOrders(){let u=session(), rr=rides(), me=users()[u.mobile], pending=rr.filter(r=>r.status==='searching'&&me.online&&me.lat&&dist({lat:me.lat,lng:me.lng},r.pickup)<=RADIUS); if(pending.length){$('ringBox').classList.add('ring'); beep()} else $('ringBox').classList.remove('ring'); $('orders').innerHTML=pending.map(r=>`<div class=item><b>New Ride Ring</b><br>${r.pickup.name.split(',')[0]} → ${r.drop.name.split(',')[0]}<br>${r.km.toFixed(1)} KM • Earning ${money(r.riderPay)}<br><button onclick="acceptRide(${r.id})">Accept</button> <button class=ghost onclick="rejectRide(${r.id})">Reject</button></div>`).join('')||'<p class=hint>No nearby ride</p>'; const done=rr.filter(r=>r.rider===u.mobile); $('earn').textContent=money(done.reduce((s,r)=>s+r.riderPay,0)); $('done').textContent=done.length}
function setOnline(v){let us=users(),u=session();us[u.mobile].online=v;saveUsers(us);showRiderOrders()} function acceptRide(id){let rr=rides(),u=session(); rr=rr.map(r=>r.id===id?{...r,status:'accepted',rider:u.mobile,riderName:u.name}:r); saveRides(rr); alert('Ride accepted')} function rejectRide(id){alert('Rejected for demo')}
function loadAdmin(){let u=session(); if(u.mobile!==OWNER_NUMBER)return location.href='index.html'; let rr=rides(), apps=get('r4Apps',[]), us=users(); $('totalOrders').textContent=rr.length; $('collection').textContent=money(rr.reduce((s,r)=>s+r.amount,0)); $('payout').textContent=money(rr.reduce((s,r)=>s+r.riderPay,0)); $('margin').textContent=money(rr.reduce((s,r)=>s+r.amount-r.riderPay,0)); $('apps').innerHTML=apps.map(a=>`<div class=item><b>${a.name}</b> ${a.role}<br>${a.mobile} • ${a.status}<br><button onclick="approve('${a.mobile}','${a.name}','${a.role}')">Approve + TEMP123</button></div>`).join('')||'<p class=hint>No applications</p>'; $('allRides').innerHTML=rr.map(r=>`<div class=item><b>${r.customerName}</b> ${r.km.toFixed(1)} KM • ${money(r.amount)}<br>Rider payout ${money(r.riderPay)} • Margin ${money(r.amount-r.riderPay)} • ${r.payment}</div>`).join('')}
function approve(m,n,role){let us=users(), apps=get('r4Apps',[]); us[m]={name:n,mobile:m,role,password:'TEMP123',approved:true,passwordChanged:false,online:false}; saveUsers(us); apps=apps.map(a=>a.mobile===m?{...a,status:'approved'}:a); set('r4Apps',apps); alert('Approved. Temporary password: TEMP123'); loadAdmin()}
