const $=id=>document.getElementById(id);
const money=n=>"₹"+Math.round(Number(n)||0);
const USERS="r4x_users",RIDES="r4x_rides",SESSION="r4x_session",COUNT="r4x_count";
let map,pickupMarker,dropMarker,routeLine,pickup={lat:31.1048,lng:77.1734,name:"Shimla"},drop=null,currentKm=0,coupon=false;
const read=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const users=()=>read(USERS,{}), rides=()=>read(RIDES,[]);
function saveUsers(v){write(USERS,v)} function saveRides(v){write(RIDES,v)}
function currentUser(){return users()[localStorage.getItem(SESSION)]||null}
function login(){const mobile=$("loginMobile").value.trim(), role=$("loginRole").value;if(!mobile)return alert("Enter mobile number");const u=users();if(!u[mobile])u[mobile]={mobile,role,name:role==="admin"?"Admin":role+" "+mobile.slice(-4),online:false,createdAt:Date.now(),couponUsed:false};else u[mobile].role=role;saveUsers(u);localStorage.setItem(SESSION,mobile);loadApp()}
function logout(){localStorage.removeItem(SESSION);location.reload()}
function resetDemo(){if(confirm("Clear demo data?")){localStorage.clear();location.reload()}}
function loadApp(){const u=currentUser();if(!u)return;$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");openPanel(u.role==="admin"?"admin":u.role);setTimeout(initMap,150);refresh()}
function openPanel(name){["customer","rider","admin"].forEach(p=>{$(p+"Panel").classList.toggle("hidden",p!==name);$("tab"+p[0].toUpperCase()+p.slice(1))?.classList.toggle("ghost",p!==name)});if(name==="customer")setTimeout(initMap,100);refresh()}
function initMap(){if(!$("map")||map)return;map=L.map("map").setView([pickup.lat,pickup.lng],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);useMyLocation(false);drawMap()}
function useMyLocation(show=true){if(!navigator.geolocation){drawMap();return}navigator.geolocation.getCurrentPosition(p=>{pickup={lat:p.coords.latitude,lng:p.coords.longitude,name:"Current Location"};$("pickupText").value="Current Location";drawMap();if(show)alert("Pickup set to current location")},()=>{drawMap();if(show)alert("Location denied, default Shimla used")})}
async function searchDrop(){const q=$("dropSearch").value.trim();if(!q)return alert("Enter drop location");const res=await fetch("https://nominatim.openstreetmap.org/search?format=json&limit=1&q="+encodeURIComponent(q));const data=await res.json();if(!data[0])return alert("Location not found");drop={lat:+data[0].lat,lng:+data[0].lon,name:data[0].display_name};drawMap();calcRoute()}
function swapLocations(){if(!drop)return alert("Search drop first");const old=pickup;pickup=drop;drop=old;$("pickupText").value=pickup.name;$("dropSearch").value=drop.name;drawMap();calcRoute()}
function drawMap(){if(!map)return;if(pickupMarker)map.removeLayer(pickupMarker);if(dropMarker)map.removeLayer(dropMarker);pickupMarker=L.marker([pickup.lat,pickup.lng]).addTo(map).bindPopup("Pickup");if(drop)dropMarker=L.marker([drop.lat,drop.lng]).addTo(map).bindPopup("Drop");map.fitBounds(drop?[[pickup.lat,pickup.lng],[drop.lat,drop.lng]]:[[pickup.lat,pickup.lng]],{padding:[35,35]})}
async function calcRoute(){if(!drop)return;let km=distance(pickup,drop);try{const url=`https://router.project-osrm.org/route/v1/driving/${pickup.lng},${pickup.lat};${drop.lng},${drop.lat}?overview=full&geometries=geojson`;const res=await fetch(url);const data=await res.json();if(data.routes&&data.routes[0]){km=data.routes[0].distance/1000;if(routeLine)map.removeLayer(routeLine);routeLine=L.geoJSON(data.routes[0].geometry,{style:{weight:5,color:"#ff3030"}}).addTo(map);map.fitBounds(routeLine.getBounds(),{padding:[35,35]})}}catch(e){}currentKm=Math.max(1,km);updateFare()}
function distance(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180;const v=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(v))}
function fare(km){return km<=3?55:km*15+10} function riderPay(km){return km<=3?40:km*12}
function updateFare(){if(!currentKm)return;const base=fare(currentKm),disc=coupon?base*.10:0,total=base-disc,rp=riderPay(currentKm),cp=total-rp;$("distance").textContent=currentKm.toFixed(2)+" KM";$("fare").textContent=money(total);$("riderPay").textContent=money(rp);$("companyPay").textContent=money(cp)}
function typeNote(){$("typeNote").textContent=$("bookingType").value==="parcel"?"Parcel limit 5 KG. Cake, liquid, fragile, cash, jewellery and illegal items are not allowed.":"Bike ride with Pickup OTP and Drop OTP."}
function applyCoupon(){const u=currentUser(),code=$("couponCode").value.trim().toUpperCase();if(code!=="WELCOME10"){coupon=false;$("couponStatus").textContent="Invalid coupon"}else if(u.couponUsed){coupon=false;$("couponStatus").textContent="WELCOME10 already used"}else{coupon=true;$("couponStatus").textContent="WELCOME10 applied: 10% off demo"}updateFare()}
function nextOrder(){const n=Number(localStorage.getItem(COUNT)||"0")+1;localStorage.setItem(COUNT,n);return "#"+String(n).padStart(3,"0")}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h)}
function otpPair(m){const h=hash(m+Date.now());return{pickup:String(3000+h%5000),drop:String(7000+(h+937)%2000)}}
function bookRide(){const u=currentUser();if(!drop||!currentKm)return alert("Search drop first");const type=$("bookingType").value,weight=Number($("parcelWeight").value||0);if(type==="parcel"&&weight>5)alert("Over 5 KG: rider may cancel or request extra amount for safety");const base=fare(currentKm),disc=coupon?base*.10:0,total=base-disc,rp=riderPay(currentKm),op=otpPair(u.mobile);const ride={id:Date.now(),orderId:nextOrder(),customerMobile:u.mobile,customerName:u.name,bookingType:type,bookingFor:$("bookingFor").value,receiver:$("receiver").value,pickup,drop,distanceKm:currentKm,fare:total,riderPay:rp,companyPay:total-rp,discount:disc,couponCode:coupon?"WELCOME10":"",pickupOtp:op.pickup,dropOtp:op.drop,status:"searching",riderMobile:"",riderName:"",createdAt:new Date().toLocaleString(),weight};const all=rides();all.unshift(ride);saveRides(all);if(coupon){const us=users();us[u.mobile].couponUsed=true;saveUsers(us);coupon=false}$("pickupOtp").textContent=op.pickup;$("dropOtp").textContent=op.drop;alert(`Order ${ride.orderId} booked. Pickup OTP ${op.pickup}, Drop OTP ${op.drop}`);refresh()}
function setOnline(on){const u=currentUser(),us=users();us[u.mobile].online=on;if(on&&navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>{us[u.mobile].lat=p.coords.latitude;us[u.mobile].lng=p.coords.longitude;saveUsers(us);refresh()},()=>{saveUsers(us);refresh()});else{saveUsers(us);refresh()}}
function acceptRide(id){const u=currentUser();saveRides(rides().map(r=>r.id===id&&r.status==="searching"?{...r,status:"accepted",riderMobile:u.mobile,riderName:u.name,acceptedAt:new Date().toLocaleString()}:r));alert("Order accepted. Ask customer for pickup OTP.");refresh()}
function startRide(id){const code=prompt("Enter pickup OTP");let ok=false;saveRides(rides().map(r=>{if(r.id===id&&r.pickupOtp===code&&r.status==="accepted"){ok=true;return{...r,status:"started",startedAt:new Date().toLocaleString()}}return r}));if(!ok)alert("Wrong pickup OTP");else{const r=rides().find(x=>x.id===id);openRoute(r.pickup,r.drop)}refresh()}
function completeRide(id){const code=prompt("Enter drop OTP");let ok=false;saveRides(rides().map(r=>{if(r.id===id&&r.dropOtp===code&&(r.status==="started"||r.status==="accepted")){ok=true;return{...r,status:"completed",completedAt:new Date().toLocaleString()}}return r}));alert(ok?"Order completed":"Wrong drop OTP");refresh()}
function openRoute(a,b){window.open(`https://www.google.com/maps/dir/?api=1&origin=${a.lat},${a.lng}&destination=${b.lat},${b.lng}&travelmode=driving`,"_blank")}
function openPoint(p){window.open(`https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}`,"_blank")}
function short(t){return !t?"":t.length>70?t.slice(0,70)+"...":t}
function refresh(){renderCustomer();renderRider();renderAdmin()}
function renderCustomer(){if(!$("customerOrders"))return;const u=currentUser();if(!u)return;const list=rides().filter(r=>r.customerMobile===u.mobile);$("customerOrders").innerHTML=list.map(r=>`<div class=item><b>${r.orderId} • ${r.status.toUpperCase()}</b>${r.bookingType} • ${r.distanceKm.toFixed(2)} KM • ${money(r.fare)}<br>Pickup: ${short(r.pickup.name)}<br>Drop: ${short(r.drop.name)}<br>Pickup OTP: <b>${r.pickupOtp}</b> • Drop OTP: <b>${r.dropOtp}</b><br>Rider: ${r.riderName||"Searching..."}<div class=actions><button class=ghost onclick='openPoint(${JSON.stringify(r.pickup)})'>Pickup</button><button class=ghost onclick='openPoint(${JSON.stringify(r.drop)})'>Drop</button><button class=ghost onclick='openRoute(${JSON.stringify(r.pickup)},${JSON.stringify(r.drop)})'>Route</button></div></div>`).join("")||"<p class=note>No orders yet.</p>"}
function renderRider(){if(!$("riderOrders"))return;const u=currentUser();if(!u)return;const rider=users()[u.mobile]||{},newOrders=rides().filter(r=>r.status==="searching");$("riderStatus").textContent=rider.online?"Online":"Offline";$("ringBox")?.classList.toggle("ring",rider.online&&newOrders.length>0);$("riderOrders").innerHTML=(rider.online?newOrders:[]).map(r=>`<div class=item><b>${r.orderId} • New ${r.bookingType}</b>${r.distanceKm.toFixed(2)} KM • Your pay ${money(r.riderPay)}<br>Pickup: ${short(r.pickup.name)}<br>Drop: ${short(r.drop.name)}<div class=actions><button onclick="acceptRide(${r.id})">Accept</button><button class=ghost onclick='openRoute(${JSON.stringify(r.pickup)},${JSON.stringify(r.drop)})'>Map</button></div></div>`).join("")||`<p class=note>${rider.online?"No new order":"Go online to receive orders"}</p>`;const mine=rides().filter(r=>r.riderMobile===u.mobile);$("myRides").innerHTML=mine.map(r=>`<div class=item><b>${r.orderId} • ${r.status.toUpperCase()}</b>${r.bookingType} • ${r.distanceKm.toFixed(2)} KM • Pay ${money(r.riderPay)}<br>Customer fare ${money(r.fare)} • Company ${money(r.companyPay)}<div class=actions>${r.status==="accepted"?`<button onclick="startRide(${r.id})">Start OTP</button>`:""}${r.status==="started"?`<button onclick="completeRide(${r.id})">Complete OTP</button>`:""}<button class=ghost onclick='openRoute(${JSON.stringify(r.pickup)},${JSON.stringify(r.drop)})'>Google Maps</button></div></div>`).join("")||"<p class=note>No accepted orders.</p>";const done=mine.filter(r=>r.status==="completed");$("riderDone").textContent=done.length;$("riderEarning").textContent=money(done.reduce((s,r)=>s+r.riderPay,0));$("settlementDue").textContent=money(done.reduce((s,r)=>s+r.companyPay,0))}
function renderAdmin(){if(!$("adminList"))return;const all=rides(),total=all.reduce((s,r)=>s+r.fare,0),payout=all.reduce((s,r)=>s+r.riderPay,0),company=all.reduce((s,r)=>s+r.companyPay,0);$("adminOrders").textContent=all.length;$("adminCollection").textContent=money(total);$("adminPayout").textContent=money(payout);$("adminCompany").textContent=money(company);$("adminList").innerHTML=all.map(r=>`<div class=item><b>${r.orderId} • ${r.status.toUpperCase()}</b>Customer: ${r.customerName} (${r.customerMobile})<br>Rider: ${r.riderName||"Not assigned"}<br>Type: ${r.bookingType} • ${r.distanceKm.toFixed(2)} KM<br>Customer ${money(r.fare)} • Rider ${money(r.riderPay)} • Company ${money(r.companyPay)}<br>Pickup OTP ${r.pickupOtp} • Drop OTP ${r.dropOtp}</div>`).join("")||"<p class=note>No orders.</p>"}
document.addEventListener("DOMContentLoaded",()=>{typeNote();if(currentUser())loadApp()});